name: Haskell-CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  push:
    branches:
      - begin-workflow
jobs:
  runhaskell:
    name: Run-Tests
    runs-on: ubuntu-latest
    steps:
      uses: actions/setup-haskell@v1.1
      uses: actions/checkout@v2
      run: runhaskell Hello.hs



