name: Haskell-CI
on:
  push:
    branches:
      - main
      - begin-workflow
  pull_request:
    branches:
      - main

jobs:
  runhaskell:
    name: Run-Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.0
      with:
        ghc-version: '8.10.4'
        cabal-version: '3.6.0.0'
    - run: runhaskell Hello.hs #hoping we get here



