name: Haskell-CI
on:
  push:
    branches:
      - main
      - begin-workflow
  pull_request:
    branches:
      - main

jobs:
  runhaskell:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
    - run: pwd
    - run: cd /home/runner/work/Haskell/Haskell
    - run: pwd
    - run: cabal test



